#! /usr/bin/env python2.4
"""
twill shell.
"""

import sys
from twill import AutoShell, execute_file

# If run from the command line, find & run any scripts put on the command
# line.  If none, drop into an interactive AutoShell.

if __name__ == '__main__':
    if len(sys.argv[1:]):
        for filename in sys.argv[1:]:
            print '>> EXECUTING FILE', filename
    
            execute_file(filename)
    else:
        AutoShell().interact()
