#! /usr/bin/env python2.4
"""
"""

import sys
from twill import AutoShell

# If run from the command line, find & run any scripts put on the command
# line.  If none, drop into an interactive AutoShell.

if __name__ == '__main__':
    if len(sys.argv[1:]):
        for filename in sys.argv[1:]:
            print '>> EXECUTING FILE', filename
    
            shell = AutoShell()
            shell.execute_file(filename)
    else:
        AutoShell().interact()
